name: checkmaster
description: CheckMaster – a fully-featured checklist manager.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  uuid: ^4.4.0
  http: ^1.2.1
  share_plus: ^9.0.0
  flutter_colorpicker: ^1.1.0
  reorderable_grid_view: ^2.2.5
  intl: ^0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
